# vim ft=yaml
# travis-ci.org definition for testkraut build (based on the PyMVPA
# configuration that is based on the nipype configuration which in turn was
# based on nipy)
#
# We pretend to be erlang because we need can't use the python support in
# travis-ci; it uses virtualenvs, they do not have numpy, scipy, matplotlib,
# and it is impractical to build them
language: erlang
env:
    - PYTHON=python PYSUF=''
    # - PYTHON=python3 PYSUF=3 : python3-numpy not currently available
install:
    # to prevent IPv6 being used for APT
    - sudo bash -c "echo 'Acquire::ForceIPv4 \"true\";' > /etc/apt/apt.conf.d/99force-ipv4"
    # The ultimate one-liner setup for NeuroDebian repository
    - bash <(wget -q -O- http://neuro.debian.net/_files/neurodebian-travis.sh)
    #- sudo apt-get install $PYTHON-dev
    - pip install six
    - sudo apt-get install -qq $PYTHON-numpy
    - sudo apt-get install -qq $PYTHON-scipy
    - sudo apt-get install -qq $PYTHON-nibabel
    - sudo apt-get install -qq $PYTHON-nose
    - sudo apt-get install -qq $PYTHON-pydot
    - sudo apt-get install -qq $PYTHON-testtools
    - sudo apt-get install -qq $PYTHON-nipype
    - sudo apt-get install -qq strace
script:
    - ls -l
    - $PYTHON -c 'from testkraut import cfg; print cfg'
    # Run only nonlabile tests
    - TESTKRAUT_TESTRUN_SKIP_DEPENDENCY_DESCRIPTION=yes make test
